language: node_js
node_js:
- '9'
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
      - DIST='web' # distribution
    - os: linux
      dist: trusty
      sudo: required
      env:
      - DIST='desktop'
    - os: osx
      env:
      - DIST='desktop'
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev ; fi
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start ; fi
install: npm install && cd dapp && npm install && cd ..
script:
- npm run test-dapp
- npm run test
before_deploy:
  - chmod +x prepare_deploy_linux.sh
  - ./prepare_deploy_linux.sh
deploy:
  - provider: s3
    bucket: wallet-development
    secret_access_key:
      secure: Majn2FTM7tRTyTiuXR6Bcso1/veE5yg+UzFf0ZKby7bUvTa60oAPmgSDFvoePnnjADDZrOp0SKBMSbE3uJW/MpFN8n8mF6p4TfPySTsVjptk5M8i9pGn7gdwXTmPtQNMCGC7dAZjsg61udbPUbx2EERmJd9Zc3W6XVKHtfqxec+/wWP7uN3bF2yxn2sbVAbLQnyPCyU8qb2p3fmlKUdRGG+I06cljEuBtKA4Er2NEqCcxNvDJwy+SqoG+5ToPfzLffW/kyNuwYJKPdqmtfnlKWjmR6ZOmEIgRSQe+5Y8hrOP6ztxnGy8GGuzx+bIsP7B7d8e8rR4ME6FtxLY/WqE9yF4H9St0KqqFfsEwKGK1UhCd7pWD7/YVaNBE8xAvBV2uxYfAYuiVRkX+bfJD2zBaj8hzI4VBV4JBpP9Hjdjp5TtqxAKtWkCW3RR6+Sj0zpL7VieFP/gCQAzro+SGZhaiTM2AnTNzx07XcOauk0ls10OLY+uenN70+fxuvAXTA5mdUJOe8DUXtvuMLAKB3gRe9sF84Ky4J1C49olvSPhVdfv48myN6v5u1m2D1ePg88OFMKK+jpkfXOk59ZbgPIBjUU+Ik7ETCDwUKl58ZNO8vD+L3XcSfuN58xj5rGiSMZF15uWo6wBiV56d8LKl2+gf02ipj9m0LA5jUukK/FcruA=
    access_key_id:
      secure: BDEFvOIGXS59CL3DzPDZ3q2AkkRdFzwgiGoyou2KEE1Kv3D7TxxTKM8cvuFSHlvGls8qronN7zgB8Zt5wEXJS6+mBotb6T8W3c5xWKyrPooTdwMsvTwtXbUiJeU6Kp6YJCkKUHDYo2XPFDGuYQXK4GBImaMsS2bTcBwM14K7oD6pTzLDERU8Ll+/1u3HtboJOy688+hWs+P2K4xUO+W+3KXGI1MNapg9QcqyzgPCByBny/uvhzc262xbpe6U/QOKEKjmZQb7mpgidrPNGk3MesepAlGg/WoM8ufmbOFBqI/gWHknOY+26oRkdzP3NHhQXHXqSZTvcEFtlGNonSCc50o8p3NoMbR673cbgbecJ0OrP6ZzAcll7SGWa5JQqpA+6Ep82jEExTWjTOUK2aQYaRgPkahVNuwmqpoXt4tvnnlIETt10O9P7Un1dmBxJn6TxIroZW+9suhbzs5UmzjB+wJU2io2/FTxNHzgGj9cRQ3FG2regirneJ4SFImf8+ZJymdc86qUE1/3fXzt3f0c3MZhm3C8ZTXEcZJuqpCNu04nxapch6G0I4NlyziTh+1ezUa6+yZs8P/NRnKcHiU+7j7AV0ewJyK92QY7dfr+LjnqYw8q9GBj1djgf0i7FVzyAAuGL52MXrnWAn3Jfypg6Zsu8nVdeToowpJTQ60m0kA=
    skip_cleanup: true
    local_dir: dapp/src
    on:
      branch: develop
      condition: $DIST = web
  - provider: s3
    bucket: wallet-staging
    secret_access_key:
      secure: Majn2FTM7tRTyTiuXR6Bcso1/veE5yg+UzFf0ZKby7bUvTa60oAPmgSDFvoePnnjADDZrOp0SKBMSbE3uJW/MpFN8n8mF6p4TfPySTsVjptk5M8i9pGn7gdwXTmPtQNMCGC7dAZjsg61udbPUbx2EERmJd9Zc3W6XVKHtfqxec+/wWP7uN3bF2yxn2sbVAbLQnyPCyU8qb2p3fmlKUdRGG+I06cljEuBtKA4Er2NEqCcxNvDJwy+SqoG+5ToPfzLffW/kyNuwYJKPdqmtfnlKWjmR6ZOmEIgRSQe+5Y8hrOP6ztxnGy8GGuzx+bIsP7B7d8e8rR4ME6FtxLY/WqE9yF4H9St0KqqFfsEwKGK1UhCd7pWD7/YVaNBE8xAvBV2uxYfAYuiVRkX+bfJD2zBaj8hzI4VBV4JBpP9Hjdjp5TtqxAKtWkCW3RR6+Sj0zpL7VieFP/gCQAzro+SGZhaiTM2AnTNzx07XcOauk0ls10OLY+uenN70+fxuvAXTA5mdUJOe8DUXtvuMLAKB3gRe9sF84Ky4J1C49olvSPhVdfv48myN6v5u1m2D1ePg88OFMKK+jpkfXOk59ZbgPIBjUU+Ik7ETCDwUKl58ZNO8vD+L3XcSfuN58xj5rGiSMZF15uWo6wBiV56d8LKl2+gf02ipj9m0LA5jUukK/FcruA=
    access_key_id:
      secure: BDEFvOIGXS59CL3DzPDZ3q2AkkRdFzwgiGoyou2KEE1Kv3D7TxxTKM8cvuFSHlvGls8qronN7zgB8Zt5wEXJS6+mBotb6T8W3c5xWKyrPooTdwMsvTwtXbUiJeU6Kp6YJCkKUHDYo2XPFDGuYQXK4GBImaMsS2bTcBwM14K7oD6pTzLDERU8Ll+/1u3HtboJOy688+hWs+P2K4xUO+W+3KXGI1MNapg9QcqyzgPCByBny/uvhzc262xbpe6U/QOKEKjmZQb7mpgidrPNGk3MesepAlGg/WoM8ufmbOFBqI/gWHknOY+26oRkdzP3NHhQXHXqSZTvcEFtlGNonSCc50o8p3NoMbR673cbgbecJ0OrP6ZzAcll7SGWa5JQqpA+6Ep82jEExTWjTOUK2aQYaRgPkahVNuwmqpoXt4tvnnlIETt10O9P7Un1dmBxJn6TxIroZW+9suhbzs5UmzjB+wJU2io2/FTxNHzgGj9cRQ3FG2regirneJ4SFImf8+ZJymdc86qUE1/3fXzt3f0c3MZhm3C8ZTXEcZJuqpCNu04nxapch6G0I4NlyziTh+1ezUa6+yZs8P/NRnKcHiU+7j7AV0ewJyK92QY7dfr+LjnqYw8q9GBj1djgf0i7FVzyAAuGL52MXrnWAn3Jfypg6Zsu8nVdeToowpJTQ60m0kA=
    skip_cleanup: true
    local_dir: dapp/src
    on:
      branch: master
      condition: $DIST = web

  - provider: s3
    bucket: wallet-desktop-builds
    secret_access_key:
      secure: Majn2FTM7tRTyTiuXR6Bcso1/veE5yg+UzFf0ZKby7bUvTa60oAPmgSDFvoePnnjADDZrOp0SKBMSbE3uJW/MpFN8n8mF6p4TfPySTsVjptk5M8i9pGn7gdwXTmPtQNMCGC7dAZjsg61udbPUbx2EERmJd9Zc3W6XVKHtfqxec+/wWP7uN3bF2yxn2sbVAbLQnyPCyU8qb2p3fmlKUdRGG+I06cljEuBtKA4Er2NEqCcxNvDJwy+SqoG+5ToPfzLffW/kyNuwYJKPdqmtfnlKWjmR6ZOmEIgRSQe+5Y8hrOP6ztxnGy8GGuzx+bIsP7B7d8e8rR4ME6FtxLY/WqE9yF4H9St0KqqFfsEwKGK1UhCd7pWD7/YVaNBE8xAvBV2uxYfAYuiVRkX+bfJD2zBaj8hzI4VBV4JBpP9Hjdjp5TtqxAKtWkCW3RR6+Sj0zpL7VieFP/gCQAzro+SGZhaiTM2AnTNzx07XcOauk0ls10OLY+uenN70+fxuvAXTA5mdUJOe8DUXtvuMLAKB3gRe9sF84Ky4J1C49olvSPhVdfv48myN6v5u1m2D1ePg88OFMKK+jpkfXOk59ZbgPIBjUU+Ik7ETCDwUKl58ZNO8vD+L3XcSfuN58xj5rGiSMZF15uWo6wBiV56d8LKl2+gf02ipj9m0LA5jUukK/FcruA=
    access_key_id:
      secure: BDEFvOIGXS59CL3DzPDZ3q2AkkRdFzwgiGoyou2KEE1Kv3D7TxxTKM8cvuFSHlvGls8qronN7zgB8Zt5wEXJS6+mBotb6T8W3c5xWKyrPooTdwMsvTwtXbUiJeU6Kp6YJCkKUHDYo2XPFDGuYQXK4GBImaMsS2bTcBwM14K7oD6pTzLDERU8Ll+/1u3HtboJOy688+hWs+P2K4xUO+W+3KXGI1MNapg9QcqyzgPCByBny/uvhzc262xbpe6U/QOKEKjmZQb7mpgidrPNGk3MesepAlGg/WoM8ufmbOFBqI/gWHknOY+26oRkdzP3NHhQXHXqSZTvcEFtlGNonSCc50o8p3NoMbR673cbgbecJ0OrP6ZzAcll7SGWa5JQqpA+6Ep82jEExTWjTOUK2aQYaRgPkahVNuwmqpoXt4tvnnlIETt10O9P7Un1dmBxJn6TxIroZW+9suhbzs5UmzjB+wJU2io2/FTxNHzgGj9cRQ3FG2regirneJ4SFImf8+ZJymdc86qUE1/3fXzt3f0c3MZhm3C8ZTXEcZJuqpCNu04nxapch6G0I4NlyziTh+1ezUa6+yZs8P/NRnKcHiU+7j7AV0ewJyK92QY7dfr+LjnqYw8q9GBj1djgf0i7FVzyAAuGL52MXrnWAn3Jfypg6Zsu8nVdeToowpJTQ60m0kA=
    skip_cleanup: true
    local_dir: $TRAVIS_BUILD_DIR/dapp/dist/
    on:
      branch: develop # remember to change it to master
      condition: $DIST = 'desktop'
